In [20]:
import warnings
warnings.filterwarnings("ignore")
%pylab inline
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


In [ ]:
# The dataset is selected from Kaggle: https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009/version/2#
# A decision tree is trained to predict the quality of wine based on given predictors.

In [21]:
data = pd.read_csv("winequality-red.csv", header=0)
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [22]:
x_data =  data.iloc[:,0:(len(data.columns)-2)]
y_data =  data.iloc[:,len(data.columns)-1]
#y_data.head()

In [ ]:
# Split the dataset into train and test and fit a decision tree and measure the performance by predicting
# the values on test data

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.20, random_state=33)

In [ ]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=20 ,min_samples_leaf=10)
clf = clf.fit(x_train,y_train)
dp = clf.decision_path(x_train)
#print(dp)

In [ ]:
from sklearn import metrics
def measure_performance(X,y,clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred=clf.predict(X)   
    if show_accuracy:
        print ("Accuracy:{0:.3f}".format(metrics.accuracy_score(y,y_pred)),"\n")

    if show_classification_report:
        print ("Classification report")
        print (metrics.classification_report(y,y_pred),"\n")
        
    if show_confusion_matrix:
        print ("Confusion matrix")
        print (metrics.confusion_matrix(y,y_pred),"\n")
        
measure_performance(x_test,y_test,clf, show_classification_report=True, show_confusion_matrix=True)

In [ ]:
# Then Train a RandomForest

In [26]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier( n_estimators=100,random_state=33)
clf = clf.fit(x_train,y_train)

Accuracy:0.691 

Classification report
             precision    recall  f1-score   support

          3       0.00      0.00      0.00         1
          4       0.00      0.00      0.00         9
          5       0.74      0.74      0.74       140
          6       0.62      0.74      0.67       128
          7       0.88      0.58      0.70        38
          8       0.00      0.00      0.00         4

avg / total       0.67      0.69      0.68       320
 

Confusion matrix
[[  0   0   1   0   0   0]
 [  0   0   5   4   0   0]
 [  0   0 104  35   1   0]
 [  0   0  31  95   2   0]
 [  0   0   0  16  22   0]
 [  0   0   0   4   0   0]] 



In [ ]:
columns = data.columns
for feature in zip(columns, clf.feature_importances_):
    print(feature)

In [ ]:
clf = clf.fit(x_train,y_train)
measure_performance(x_test,y_test,clf, show_classification_report=True, show_confusion_matrix=False)